version: '3'
services:
 web:
  build:
   context: ./
   dockerfile: web.docker
  volumes:
   - ./:/var/www/
   - ./vhost.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "3207:80"
  links:
   - app
  restart: always
 app:
  build:
   context: ./
   dockerfile: app.docker
  volumes:
   - ./:/var/www/
   - ./php.ini:/usr/local/etc/php/php.ini
  restart: always
networks:
  default:
    external:
      name: satori-network-1
